# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: Create env file
          run:
          touch .env
          echo JWT_SECRET=et4UFbs4Hk1lRrhwdkBW12xmcBzRpulnJf1+7VIwMzey+ddY1d86DEYR4DDlLtICB7rftT3YK5nY/P3fQ8IKGPEtfuuYB5zGzVYpD5walxvI+KDPzFzbbYUotgxnSIZJcZ6l63KBzr84RdD64hRJYljSxyTn80MalqXXLrzA4VA0BoL8e65vhG/i/G+AKS55w7RPlfOyjbY/tSglgJBTsuvXNtwJUYT94wg2CoHZv8J4Z8bfuwWY81WTcJW9NGhHQga80VIjwqUihPvFhfu+X4T3I42T1ndVy3Xw3XucWzT6dZElZJZFVasR1rfxkt6JYO3sDXYl0fLSz6fvz7neKA==et4UFbs4Hk1lRrhwdkBW12xmcBzRpulnJf1+7VIwMzey+ddY1d86DEYR4DDlLtICB7rftT3YK5nY/P3fQ8IKGPEtfuuYB5zGzVYpD5walxvI+KDPzFzbbYUotgxnSIZJcZ6l63KBzr84RdD64hRJYljSxyTn80MalqXXLrzA4VA0BoL8e65vhG/i/G+AKS55w7RPlfOyjbY/tSglgJBTsuvXNtwJUYT94wg2CoHZv8J4Z8bfuwWY81WTcJW9NGhHQga80VIjwqUihPvFhfu+X4T3I42T1ndVy3Xw3XucWzT6dZElZJZFVasR1rfxkt6JYO3sDXYl0fLSz6fvz7neKA== >> .env
          echo SALT = 10 >> .env
          echo JWT_LIFE=300 >> .env
          cat .env
    - run: npm test
